### ISSUE TITLE
10阶偶尔会出现错位

### ISSUE THREAD

**Issue by chiga0** [pengfeiw/rubiks-cube#1]
![image](https://user-images.githubusercontent.com/24784430/158921448-9cccf3b4-c15b-455f-9c22-3aa7caa41a58.png)

**Comment by pengfeiw** [comment]
你好😀，能说明下复现步骤和环境（浏览器版本信息）吗，我这边之前测试了很久，没有出现过这个问题。

**Comment by seabean1999** [comment]
我试玩了一下10阶，很容易也穿模了

**Comment by seabean1999** [comment]
![](https://gitee.com/lin-xibin/image-repository/raw/79e44942024dfd376eb3ebd1d9fa2f518d56c9c5/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-03-19%20005429.jpg)

**Comment by kyya** [comment]
![WeChat Screenshot_20220319113712](https://user-images.githubusercontent.com/13448248/159105216-6c90dad2-b6af-42ef-986d-d68c0ed56707.png)

二阶也有这个问题。

复现步骤：快速随机转动

**Comment by pengfeiw** [comment]
> ![WeChat Screenshot_20220319113712](https://user-images.githubusercontent.com/13448248/159105216-6c90dad2-b6af-42ef-986d-d68c0ed56707.png)
> 
> 二阶也有这个问题。
> 
> 复现步骤：快速随机转动

thanks, 我尽快修复，应该是可能是判断旋转角度的处理有点问题。

**Comment by bxclib2** [comment]
3 阶也挺容易错位的，有的时候会卡在一个位置然后就乱了

**Comment by bxclib2** [comment]
我是用iphone xr测试的，是不是只有手机容易这样呢

**Comment by bxclib2** [comment]
<img width="142" alt="Screenshot 2022-03-19 at 12 36 54 PM" src="https://user-images.githubusercontent.com/47888430/159107007-e941658e-6013-43fb-848e-6f58941f5074.png">

**Comment by Hiltoness** [comment]
pc也会，快速转动就穿模错位

**Comment by pengfeiw** [comment]
@Hiltoness @Kyya @garygao12580 @bxclib2 快速转动导致穿模错位的问题，原因是上一次的旋转动画还未结束，又开始了新的一轮操作导致的。目前我更新了一下这个问题，你们可以再试一试， [fix](https://github.com/pengfeiw/rubiks-cube/commit/cfc1a7ede40a77a37932fd43113495c15ac9ff49)。

**Comment by pengfeiw** [comment]
我自己的手机和电脑设备都已经测试过了

**Comment by chiga0** [comment]
> 我自己的手机和电脑设备都已经测试过了

好了，赞👍
