### ISSUE TITLE
不能赞赏吗？我没有找到赞赏码在哪里

### ISSUE THREAD

**Issue by shijianzugouniai** [pengfeiw/rubiks-cube#2]

**Comment by pengfeiw** [comment]
谢谢，你的认可就是最大的赞赏。

**Comment by shijianzugouniai** [comment]
我认为赞赏是尊重开发者的劳动成果，虽然我是一个小白，可能也能给不了太多的物质支持

**Comment by pengfeiw** [comment]
开发这个也是因为我自己对其感兴趣，如果对其他人有帮助的话，那就更好了。如果你对我写的小玩意感兴趣或者有什么疑惑不懂的地方，也可以咨询我，知无不言。

**Comment by shijianzugouniai** [comment]
大佬您好谦和，我已经将您的小项目分享给我的朋友啦，感谢大佬分享

**Comment by shijianzugouniai** [comment]
谢谢您的回答，我待会可能就把issue关了，不打扰啦(其实还是想要一个赞赏码，虽然sponsor可能没有很多)

**Comment by pengfeiw** [comment]
'(其实还是想要一个赞赏码，虽然sponsor可能没有很多)'    真的不用了，钱留着自己花多好😁，互联网上的知识很多都是免费，我也是白嫖别人的资源过来的。
